name: helm-deploy
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
on:
  workflow_dispatch:
jobs:
  build:
    #if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com' || cloudbees.api.url == 'https://api.cloudbees.io'
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: get source code
        uses: cloudbees-io/checkout@v1
      - name: Validate action
        uses: docker://amazon/aws-cli:2.15.54
        run: |
          TESTING_SHA=$(cat .cloudbees/testing/action.yml | sha1sum)
          ORIGINAL_SHA=$(sed -e 's|docker://public.ecr.aws/l7o7z1g8/actions/|docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/|g' < action.yml | sha1sum)
          if [ "${TESTING_SHA}" != "${ORIGINAL_SHA}" ]; then
            echo "Original action different from testing action"
            exit 1
          fi
      - name: Run bats tests
        uses: docker://bats/bats:v1.10.0
        with:
          entrypoint: /opt/bats/bin/bats
          args: .
      - name: Login to AWS
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.oidc_staging_iam_role }}
          role-duration-seconds: "3600"

  # deploy:
  #   permissions:
  #     scm-token-own: read
  #     id-token: write
  #   steps:
  #     - uses: cloudbees-io/checkout@v1
  #       name: checkout

  #     - name: Login to AWS
  #       uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
  #       with:
  #         aws-region: us-east-1
  #         role-to-assume: ${{ vars.oidc_staging_iam_role }}
  #         role-duration-seconds: "3600"

      # - id: ecrconfig
      #   name: Configure container registry for staging ECR
      #   uses: cloudbees-io/configure-ecr-credentials@v1

      # - name: docker build and publish
      #   uses: cloudbees-io/kaniko@v1
      #   with:
      #     destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/demos/helm-demo:${{ cloudbees.scm.sha }}
      #     context: ${{ cloudbees.workspace }}
      #     labels: maintainer=sdp-pod-3,email=engineering@cloudbees.com
      #     registry-mirrors: 020229604682.dkr.ecr.us-east-1.amazonaws.com/docker-hub


      # - uses: cloudbees-io/configure-oci-credentials@v1
      #   name: Set up Docker Hub registry
      #   kind: deploy
      #   with:
      #     registry: https://index.docker.io/v1/
      #     username: corinnekrych
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - uses: cloudbees-io/kaniko/.cloudbees/testing
      #   name: Push image to OCI registry
      #   with:
      #     destination: index.docker.io/corinnekrych/go-hello-world-docker:1.0.1-${{cloudbees.version}}
      #     labels: app=cbp